#!/usr/bin/env bash

if [[ $# -lt 2 ]]; then
	echo "Usage: git_change_author <name> <email>" >&2
	return 1
fi

local authorName="$1"
local authorEmail="$2"

export FILTER_AUTHOR_NAME="$authorName"
export FILTER_AUTHOR_EMAIL="$authorEmail"

git filter-branch -f --env-filter '
GIT_AUTHOR_NAME="$FILTER_AUTHOR_NAME"; GIT_AUTHOR_EMAIL="$FILTER_AUTHOR_EMAIL";
GIT_COMMITTER_NAME="$FILTER_AUTHOR_NAME"; GIT_COMMITTER_EMAIL="$FILTER_AUTHOR_EMAIL";
' HEAD

unset FILTER_AUTHOR_NAME FILTER_AUTHOR_EMAIL
