#!/usr/bin/env bash

# https://stackoverflow.com/questions/454734/how-can-one-change-the-timestamp-of-an-old-commit-in-git
# https://stackoverflow.com/questions/1186535/how-do-i-modify-a-specific-commit

# Format iso8601: YYYY-MM-DD HH:MM:SS
timestamp=$1

# --date=now

# git rebase --interactive HEAD~2

GIT_AUTHOR_DATE=format:iso8601:"$timestamp" GIT_COMMITTER_DATE=format:iso8601:"$timestamp" git commit --amend --no-edit --date "$timestamp"
