#!/usr/bin/env bash

set -o pipefail

# Define colors
GREEN='\033[0;32m'
RED='\033[0;31m'

# Function to print messages in color and set terminal output to no color after
# $1: color, from the predefined ones or an ANSI escape code
# $2: text to output
# function print_color() {
# 	echo "${!1}${2}\033[0m"
# }

# Function to generate a passphrase with 128 bits of entropy
function generate_passphrase() {
	ulimit -c 0

	dd if=/dev/urandom bs=32 count=1 2>/dev/null | base64 -b 0
}

# Function to generate a SSH key for a service
# $1: SSH key name
# $2: SSH key comment
PASSPHRASE="$(generate_passphrase)"
SSH_KEY_PATH="$HOME/.ssh/$1"

# Generate SSH key if it does not exist
if [ -f "$SSH_KEY_PATH" ]; then
	# print_color RED "The ssh key '$1' already exists"
	echo "The ssh key '$1' already exists"
	exit 1
fi

# Generate SSH key if it does not exist
# print_color GREEN "Generating ssh key '$1'"
echo "Generating ssh key '$1'"
ssh-keygen -t ed25519 -f "$SSH_KEY_PATH" -C "$2" -N "$PASSPHRASE"

# print_color GREEN "Adding ssh key '$1'"
echo "Adding ssh key '$1'"

AUTO_ADD_SCRIPT=$(umask 077 && mktemp)
trap 'rm -f "$AUTO_ADD_SCRIPT"' EXIT INT TERM
cat > "$AUTO_ADD_SCRIPT" <<-ASKPASS
#!/bin/sh
echo "$PASSPHRASE"
ASKPASS
chmod 500 "$AUTO_ADD_SCRIPT"

# Add ssh keys to the ssh-agent and therefore store passphrase in the keychain
DISPLAY=1 SSH_ASKPASS="$AUTO_ADD_SCRIPT" ssh-add --apple-use-keychain "$SSH_KEY_PATH" < /dev/null

rm -f "$AUTO_ADD_SCRIPT"
